version: '3.8'

services:
  frontend_app:
    build: .
    container_name: frontend_app
    ports:
      - "5001:5001"
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"