version: '3.8'

services:
  frontend_app:
    build: ./frontend_app
    container_name: frontend_app
    ports:
      - "8080:8080"
    restart: always

  backend_app:
    build: ./backend_app
    container_name: backend_app
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MY_SECRET_KEY=kljadskl10248120318znx
      - JWT_SECRET_KEY=jwtsecretkey10248120318znx
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=iesproject
      - DATABASE_PASSWORD=Ml@Iesproject88
      - DATABASE_NAME=iesprojects
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ml@Root88
      MYSQL_DATABASE: iesprojects
      MYSQL_USER: iesproject
      MYSQL_PASSWORD: Ml@Iesproject88
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"

volumes:
  mysql_data: