version: '3.8'

services:
  frontend_app:
    build: ./frontend_app
    container_name: frontend_app
    ports:
      - "5001:5001"
    restart: always

  backend_app:
    build: ./backend_app
    container_name: backend_app
    ports:
      - "5000:5000"
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"